worker_processes auto;

events {
    worker_connections 1024;
}

http {

    # ============================
    # Balanceo entre APP1 y APP2
    # ============================
    upstream app_pool {
        server app1:8000;
        server app2:8000;
    }

    # ============================
    # Servidor principal
    # ============================
    server {
        listen 80;

        # ---------------------------------------
        # Aplicación principal (Django/Gunicorn)
        # ---------------------------------------
        location / {
            proxy_pass http://app_pool/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ---------------------------------------
        # API de Administración de Archivos
        # ---------------------------------------
        location /api/files/ {
            proxy_pass http://api_files:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ---------------------------------------
        # API de Soporte
        # ---------------------------------------
        location /api/support/ {
            proxy_pass http://api_support:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # ---------------------------------------
        # API de Cobranza
        # ---------------------------------------
        location /api/billing/ {
            proxy_pass http://api_billing:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}

# docker compose build
# docker compose up -d