baseURL = '/'
languageCode = 'es'
title = 'Factupid'
theme = "ananke"

[params]
  custom_css = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Console"
    url = "http://localhost:8000/console/"
    weight = 1

  [[menu.main]]
    name = "Invoice"
    url = "http://localhost:8000/invoice/"
    weight = 2

  [[menu.main]]
    name = "CFDI"
    url = "http://localhost:8000/cfdi/"
    weight = 3
