# Generated by Django 5.0.2 on 2024-05-18 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('caracteristicas', models.TextField()),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual'), ('bajo consumo', 'Bajo consumo')], max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limite_operaciones_dia', models.IntegerField()),
                ('limite_operaciones_plan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SelectedService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(unique=True)),
                ('service_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('app', 'App'), ('api', 'API')], max_length=100)),
                ('url_servicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='console.service')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.plan')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.service')),
            ],
        ),
        migrations.CreateModel(
            name='Service_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=True)),
                ('fechaVigenciaInicio', models.DateField()),
                ('fechaVigenciaFin', models.DateField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.plan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='console.service')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('service', 'plan')},
            },
        ),
    ]
