# Generated by Django 5.0.3 on 2024-06-27 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_clienteservicio_delete_user_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activate', models.DateTimeField(auto_now_add=True)),
                ('date_cutoff', models.DateField()),
                ('no_stamped_day', models.IntegerField(default=0)),
                ('idPlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='console.plan')),
                ('idService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.service')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ClienteServicio',
        ),
    ]
