# Generated by Django 5.0.3 on 2024-05-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correoElectronico', models.EmailField(max_length=254)),
                ('rfc', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('tipoDeCliente', models.CharField(max_length=100)),
                ('certificado', models.FileField(upload_to='certificados/')),
                ('llave', models.FileField(upload_to='llaves/')),
                ('contrasena', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=100)),
                ('noExterior', models.CharField(max_length=100)),
                ('noInterior', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('localidad', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigoPostal', models.CharField(max_length=100)),
            ],
        ),
    ]
