# Generated by Django 5.0.3 on 2024-06-28 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_user_service_delete_clienteservicio'),
        ('console', '0010_customer'),
    ]

    operations = [
    ]
