# Generated by Django 5.0.3 on 2024-07-31 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_merge_20240627_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('idSocio', models.TextField()),
                ('urlSignManifest', models.TextField()),
                ('password', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='service_plan',
            name='supplierStamp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='console.supplierstamp'),
        ),
    ]
