# Generated by Django 5.0.3 on 2024-08-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_supplierstamp_service_plan_supplierstamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_service',
            old_name='no_stamped_day',
            new_name='cont_stamped',
        ),
    ]
