# Generated by Django 5.0.3 on 2024-08-01 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_rename_no_stamped_day_user_service_cont_stamped'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='idServicePlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='console.service_plan'),
        ),
    ]
