# Generated by Django 5.0.3 on 2024-08-01 22:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0014_user_service_idserviceplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_service',
            unique_together={('idUser', 'idService', 'idPlan')},
        ),
    ]
