# Generated by Django 5.0.3 on 2024-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0016_alter_user_service_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_plan',
            name='tipo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
