# Generated by Django 5.0.3 on 2024-08-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0017_service_plan_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_plan',
            name='tipo',
        ),
    ]
