# Generated by Django 5.0.3 on 2024-09-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0018_remove_service_plan_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_service',
            name='cont_stamped',
        ),
    ]
