# Generated by Django 5.0.3 on 2024-09-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0019_remove_user_service_cont_stamped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_plan',
            name='usuario',
        ),
        migrations.AddField(
            model_name='user_service',
            name='cont_stamped_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_service',
            name='cont_stamped_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_service',
            name='stamp',
            field=models.IntegerField(default=0),
        ),
    ]
