# Generated by Django 5.0.3 on 2024-11-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0021_alter_customer_id_alter_plan_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_service',
            name='aceptarTerminos',
            field=models.BooleanField(default=False),
        ),
    ]
