# Generated by Django 5.1.4 on 2025-04-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0022_user_service_aceptarterminos'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='enviar_pdf',
            field=models.BooleanField(default=True, help_text='¿Adjuntar PDF en correo?'),
        ),
    ]
