# Generated by Django 5.1.4 on 2025-04-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0023_service_enviar_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='enviar_pdf',
            field=models.BooleanField(default=False, help_text='¿Adjuntar PDF en correo?'),
        ),
    ]
