# Generated by Django 5.1 on 2025-11-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0024_alter_service_enviar_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierstamp',
            name='token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplierstamp',
            name='usuario_cliente',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
