# Generated by Django 5.1.4 on 2025-11-23 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0025_supplierstamp_token_supplierstamp_usuario_cliente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplierstamp",
            name="token",
        ),
        migrations.RemoveField(
            model_name="supplierstamp",
            name="usuario_cliente",
        ),
    ]
