# Generated by Django 5.1.4 on 2025-04-29 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informacionaduanera',
            options={'ordering': ['aduana'], 'verbose_name': 'Información Aduanera', 'verbose_name_plural': 'Informaciones Aduaneras'},
        ),
        migrations.RenameField(
            model_name='receptor',
            old_name='c_RecidenciaFiscal',
            new_name='c_ResidenciaFiscal',
        ),
        migrations.AlterField(
            model_name='acuentaterceros',
            name='domicilioFiscalACuentaTerceros',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='acuentaterceros',
            name='rfcACuentaTerceros',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='certificado',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='sello',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='subTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='tipoCambio',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='version',
            field=models.CharField(default='4.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='conceptos',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='conceptos',
            name='descuento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='conceptos',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='conceptos',
            name='valorUnitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='emisor',
            name='c_RegimenFiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfdi.regimenfiscal'),
        ),
        migrations.AlterField(
            model_name='emisor',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emisor',
            name='rfc',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='impuestos',
            name='base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='impuestos',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='impuestostotales',
            name='base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='impuestostotales',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='impuestostotales',
            name='totalImpuestosRetenidos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='impuestostotales',
            name='totalImpuestosTraslados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='decimales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='porcentaje_variacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='cantidad',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='parte',
            name='valorUnitario',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='receptor',
            name='rfc',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='timbrefiscaldigital',
            name='fechaTimbrado',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timbrefiscaldigital',
            name='leyenda',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timbrefiscaldigital',
            name='selloCFD',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='timbrefiscaldigital',
            name='selloSAT',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='timbrefiscaldigital',
            name='uuid',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterModelTable(
            name='informacionaduanera',
            table='cfdi_informacionaduanera',
        ),
    ]
