# Generated by Django 5.1.4 on 2025-04-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0002_alter_informacionaduanera_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='c_FormaPago',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
