# Generated by Django 5.1.4 on 2025-04-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0003_alter_formapago_c_formapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportacion',
            name='c_Exportacion',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
