# Generated by Django 5.1.4 on 2025-04-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0004_alter_exportacion_c_exportacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicidad',
            name='c_Periodicidad',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
