# Generated by Django 5.1.4 on 2025-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0005_alter_periodicidad_c_periodicidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meses',
            name='c_Meses',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
