# Generated by Django 5.1.4 on 2025-04-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0006_alter_meses_c_meses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporelacion',
            name='c_TipoRelacion',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
