# Generated by Django 5.1.4 on 2025-04-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0007_alter_tiporelacion_c_tiporelacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claveprodserv',
            name='c_ClaveProdServ',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
