# Generated by Django 5.1.4 on 2025-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0008_alter_claveprodserv_c_claveprodserv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoimp',
            name='c_ObjetoImp',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
