# Generated by Django 5.1.4 on 2025-04-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0009_alter_objetoimp_c_objetoimp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impuesto',
            name='c_Impuesto',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
