# Generated by Django 5.1.4 on 2025-04-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0010_alter_impuesto_c_impuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aduana',
            name='c_Aduana',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
    ]
