# Generated by Django 5.1.4 on 2025-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0011_alter_aduana_c_aduana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patenteaduanal',
            name='c_PatenteAduanal',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
