# Generated by Django 5.1.4 on 2025-04-30 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0012_alter_patenteaduanal_c_patenteaduanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuentaterceros',
            name='idConcepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aCuentaTerceros', to='cfdi.conceptos'),
        ),
        migrations.AlterField(
            model_name='complementoconcepto',
            name='idConcepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complementoConcepto', to='cfdi.conceptos'),
        ),
        migrations.AlterField(
            model_name='cuentapredial',
            name='idConcepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentaPredial', to='cfdi.conceptos'),
        ),
        migrations.AlterField(
            model_name='impuestos',
            name='idComprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='cfdi.conceptos'),
        ),
        migrations.AlterField(
            model_name='informacionaduanera',
            name='idConcepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informacionAduanera', to='cfdi.conceptos'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='idConcepto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parte', to='cfdi.conceptos'),
        ),
    ]
