# Generated by Django 5.1.4 on 2025-05-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0013_alter_acuentaterceros_idconcepto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informacionglobal',
            options={'verbose_name_plural': 'Información global'},
        ),
        migrations.AlterField(
            model_name='claveprodserv',
            name='palabras_similares',
            field=models.CharField(blank=True, max_length=99999, null=True),
        ),
        migrations.AlterField(
            model_name='claveunidad',
            name='nombre',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='claveunidad',
            name='simbolo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pais',
            name='formato_rfc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usocfdi',
            name='c_UsoCFDI',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
