# Generated by Django 5.1.4 on 2025-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0014_alter_informacionglobal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfdirelacionados',
            name='uuid',
            field=models.CharField(default=1, max_length=255, verbose_name='UUID relacionado'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CfdiRelacionado',
        ),
    ]
