# Generated by Django 5.1.4 on 2025-05-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0015_cfdirelacionados_uuid_delete_cfdirelacionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='noCertificado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
