# Generated by Django 5.1.4 on 2025-05-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0016_alter_comprobante_nocertificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='fecha',
            field=models.DateField(),
        ),
    ]
