# Generated by Django 5.1.4 on 2025-05-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0017_alter_comprobante_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigopostal',
            name='c_CodigoPostal',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
