# Generated by Django 5.1.4 on 2025-05-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0018_alter_codigopostal_c_codigopostal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartaporte',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.AddField(
            model_name='cartaporte',
            name='ComprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartas_porte', to='cfdi.comprobante'),
        ),
    ]
