# Generated by Django 5.1.4 on 2025-05-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0019_remove_cartaporte_facturacartaportetraslado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobante',
            old_name='fecha',
            new_name='fechaEmision',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='fechaPago',
            field=models.DateField(default='2025-05-01'),
            preserve_default=False,
        ),
    ]
