# Generated by Django 5.1.4 on 2025-05-10 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0020_rename_fecha_comprobante_fechaemision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteCartaPorteTraslado',
            fields=[
            ],
            options={
                'verbose_name': 'Comprobante carta Porte Traslado',
                'verbose_name_plural': 'Comprobante carta Porte Traslados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cfdi.comprobante',),
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='ComprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='ComprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AlterField(
            model_name='cartaporte',
            name='ComprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartas_porte', to='cfdi.comprobantecartaportetraslado'),
        ),
    ]
