# Generated by Django 5.1.4 on 2025-05-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0021_comprobantecartaportetraslado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartaporte',
            options={'verbose_name': 'Carta Porte Traslado', 'verbose_name_plural': 'Carta Porte Traslados'},
        ),
        migrations.AlterModelOptions(
            name='domicilio',
            options={'verbose_name': 'Domicilio', 'verbose_name_plural': 'Domicilioss'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'verbose_name': 'Ubicación', 'verbose_name_plural': 'Ubicaciones'},
        ),
    ]
