# Generated by Django 5.1.4 on 2025-05-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0022_alter_cartaporte_options_alter_domicilio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposcomplemento',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipos de Complemento', 'verbose_name_plural': 'Tipos de Complemento'},
        ),
        migrations.RenameField(
            model_name='tiposcomplemento',
            old_name='monbre',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipo_documento',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('plantilla', 'Plantilla'), ('timbrado', 'Timbrado')], default='borrador', max_length=10),
        ),
        migrations.AlterField(
            model_name='timbrefiscaldigital',
            name='version',
            field=models.CharField(default='1.1', max_length=5),
        ),
    ]
