# Generated by Django 5.1.4 on 2025-05-12 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0023_alter_tiposcomplemento_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartaporte',
            old_name='ComprobanteCartaPorteTraslado',
            new_name='comprobanteCartaPorteTraslado',
        ),
    ]
