# Generated by Django 5.1.4 on 2025-05-15 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0024_rename_comprobantecartaportetraslado_cartaporte_comprobantecartaportetraslado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addenda',
            name='addenda',
            field=models.CharField(blank=True, choices=[('siemens_gamesa', 'SIEMENS GAMESA'), ('grupo_ado', 'Grupo ADO'), ('waldos', 'Waldos'), ('terra_multitransportes', 'Terra Multitransportes')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='AddendaGrupoADO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_addenda', models.CharField(blank=True, choices=[('pedido_capex', 'Pedido CAPEX'), ('refencia', 'Referencia'), ('pedido_jde', 'Pedido JDE'), ('nota_consumo', 'Nota de consumo')], max_length=50, null=True)),
                ('pedido', models.CharField(max_length=100)),
                ('addenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_ado', to='cfdi.addenda')),
            ],
            options={
                'verbose_name': 'Addenda Grupo ADO',
                'verbose_name_plural': 'Addendas Grupos ADOS',
            },
        ),
        migrations.CreateModel(
            name='AddendaSiemensGamesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodocumento', models.CharField(blank=True, choices=[('factura', 'FACTURA'), ('nota_cargo', 'Nota de cargo'), ('nota_credito', 'Nota de crédito')], max_length=50, null=True)),
                ('numero_orden', models.CharField(max_length=100)),
                ('nota_entrega', models.CharField(max_length=100)),
                ('addenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siemens_gamesa', to='cfdi.addenda')),
            ],
            options={
                'verbose_name': 'Addenda Siemens Gamesa',
                'verbose_name_plural': 'Addendas Siemens Gamesas',
            },
        ),
        migrations.CreateModel(
            name='AddendaTerraMultitransportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenedor', models.CharField(max_length=100)),
                ('reservacion', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retencion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('addenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terra_multitransportes', to='cfdi.addenda')),
            ],
            options={
                'verbose_name': 'Addenda Terra Multitransporte',
                'verbose_name_plural': 'Addenda Terra Multitransportes',
            },
        ),
        migrations.CreateModel(
            name='AddendaWaldos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=100)),
                ('addenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waldos', to='cfdi.addenda')),
            ],
            options={
                'verbose_name': 'Addenda Waldo',
                'verbose_name_plural': 'Addenda Waldos',
            },
        ),
    ]
