# Generated by Django 5.1.4 on 2025-05-16 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0025_alter_addenda_addenda_addendagrupoado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendagrupoado',
            name='addenda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_ado', to='cfdi.addenda'),
        ),
        migrations.AlterField(
            model_name='addendasiemensgamesa',
            name='addenda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='siemens_gamesa', to='cfdi.addenda'),
        ),
        migrations.AlterField(
            model_name='addendawaldos',
            name='addenda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waldos', to='cfdi.addenda'),
        ),
    ]
