# Generated by Django 5.1.4 on 2025-05-16 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0026_alter_addendagrupoado_addenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addendaterramultitransportes',
            name='addenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terra_multitransportes', to='cfdi.addenda'),
        ),
    ]
