# Generated by Django 5.1.4 on 2025-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0027_alter_addendaterramultitransportes_addenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impuestos',
            old_name='idComprobante',
            new_name='idConcepto',
        ),
        migrations.AddField(
            model_name='impuestos',
            name='incluido',
            field=models.BooleanField(default=False, verbose_name='¿Incluido en el precio?'),
        ),
    ]
