# Generated by Django 5.1.4 on 2025-05-23 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0028_rename_idcomprobante_impuestos_idconcepto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteNomina12',
            fields=[
            ],
            options={
                'verbose_name': 'Comprobante Nomina 1.2',
                'verbose_name_plural': 'Comprobante Nomina 12',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cfdi.comprobante',),
        ),
    ]
