# Generated by Django 5.1.4 on 2025-05-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0030_remove_nomina_banco_remove_deduccion_factura_nomina_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('c_Banco', models.CharField(blank=True, max_length=5, primary_key=True, serialize=False, verbose_name='Clave de Banco')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Nombre o razón social')),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha inicio de vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha inicio de vigencia')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['c_Banco'],
            },
        ),
        migrations.CreateModel(
            name='OrigenRecurso',
            fields=[
                ('c_OrigenRecurso', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Clave de Origen del Recurso')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Origen del Recurso',
                'verbose_name_plural': 'Origenes del Recurso',
                'ordering': ['c_OrigenRecurso'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicidadPago',
            fields=[
                ('c_PeriodicidadPago', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Clave de Periodicidad de Pago')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha inicio de vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha fin de vigencia')),
            ],
            options={
                'verbose_name': 'Periodicidad de Pago',
                'verbose_name_plural': 'Periodicidades de Pago',
                'ordering': ['c_PeriodicidadPago'],
            },
        ),
        migrations.CreateModel(
            name='RiesgoPuesto',
            fields=[
                ('c_RiesgoPuesto', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Clave de Riesgo Puesto')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha inicio de vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha fin de vigencia')),
            ],
            options={
                'verbose_name': 'Riesgo Puesto',
                'verbose_name_plural': 'Riesgos Puesto',
                'ordering': ['c_RiesgoPuesto'],
            },
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('c_TipoContrato', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Clave de Tipo de Contrato')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
                'ordering': ['c_TipoContrato'],
            },
        ),
        migrations.CreateModel(
            name='TipoJornada',
            fields=[
                ('c_TipoJornada', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Clave de Tipo de Jornada')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Jornada',
                'verbose_name_plural': 'Tipos de Jornada',
                'ordering': ['c_TipoJornada'],
            },
        ),
        migrations.CreateModel(
            name='TipoNomina',
            fields=[
                ('c_TipoNomina', models.CharField(blank=True, max_length=5, primary_key=True, serialize=False)),
                ('opcion', models.CharField(blank=True, max_length=30, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRegimen',
            fields=[
                ('c_TipoRegimen', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Clave del Tipo de Régimen')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha inicio de vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha fin de vigencia')),
            ],
            options={
                'verbose_name': 'Tipo de Régimen',
                'verbose_name_plural': 'Tipos de Régimen',
                'ordering': ['c_TipoRegimen'],
            },
        ),
    ]
