# Generated by Django 5.1.4 on 2025-05-24 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0031_banco_origenrecurso_periodicidadpago_riesgopuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfdi.banco'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='origen_recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfdi.origenrecurso'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='periodicidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfdi.periodicidadpago'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='riesgo_puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfdi.riesgopuesto'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='tipo_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.tipocontrato', verbose_name='Tipo de contrato'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='tipo_jornada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.tipojornada', verbose_name='Tipo de jornada'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='tipo_regimen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfdi.tiporegimen'),
        ),
    ]
