# Generated by Django 5.1.4 on 2025-05-24 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0032_nomina_banco_nomina_origen_recurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='tipo_nomina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfdi.tiponomina'),
        ),
    ]
