# Generated by Django 5.1.4 on 2025-05-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0033_nomina_tipo_nomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sindicalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(blank=True, max_length=2, null=True, unique=True)),
            ],
        ),
    ]
