# Generated by Django 5.1.4 on 2025-05-24 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0034_genero_sindicalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.genero', verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='nomina',
            name='sindicalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.sindicalizado', verbose_name='Sindicalizado'),
        ),
    ]
