# Generated by Django 5.1.4 on 2025-05-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0035_nomina_genero_nomina_sindicalizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPercepcion',
            fields=[
                ('c_TipoPercepcion', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Clave del Tipo de Percepción')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha inicio de vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha fin de vigencia')),
            ],
            options={
                'verbose_name': 'Tipo de Percepción',
                'verbose_name_plural': 'Tipos de Percepción',
                'ordering': ['c_TipoPercepcion'],
            },
        ),
        migrations.CreateModel(
            name='Percepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, verbose_name='Clave')),
                ('importe_exento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Exento')),
                ('importe_gravado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Gravado')),
                ('comprobanteNomina12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominaPercepciones', to='cfdi.comprobantenomina12')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percepciones', to='cfdi.nomina')),
                ('tipo_percepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.tipopercepcion', verbose_name='Tipo de Percepción')),
            ],
            options={
                'verbose_name': 'Percepción',
                'verbose_name_plural': 'Percepciones',
            },
        ),
    ]
