# Generated by Django 5.1.4 on 2025-05-24 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0036_tipopercepcion_percepcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeduccion',
            fields=[
                ('c_TipoDeduccion', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Clave del Tipo de Deducción')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha inicio de vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha fin de vigencia')),
            ],
            options={
                'verbose_name': 'Tipo de Deducción',
                'verbose_name_plural': 'Tipos de Deducción',
                'ordering': ['c_TipoDeduccion'],
            },
        ),
        migrations.CreateModel(
            name='Deduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, verbose_name='Clave')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe')),
                ('comprobanteNomina12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominaDeducciones', to='cfdi.comprobantenomina12')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducciones', to='cfdi.nomina')),
                ('tipo_deduccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.tipodeduccion', verbose_name='Tipo de Deducción')),
            ],
            options={
                'verbose_name': 'Deducción',
                'verbose_name_plural': 'Deducciones',
            },
        ),
    ]
