# Generated by Django 5.1.4 on 2025-05-24 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0037_tipodeduccion_deduccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOtroPago',
            fields=[
                ('c_TipoOtroPago', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Clave del Tipo de Otro Pago')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('fecha_inicio_vigencia', models.DateField(verbose_name='Fecha inicio de vigencia')),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha fin de vigencia')),
            ],
            options={
                'verbose_name': 'Tipo de Otro Pago',
                'verbose_name_plural': 'Tipos de Otros Pagos',
                'ordering': ['c_TipoOtroPago'],
            },
        ),
        migrations.CreateModel(
            name='OtroPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=20, null=True, verbose_name='Clave')),
                ('importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe')),
                ('comprobanteNomina12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nominaOtrosPagos', to='cfdi.comprobantenomina12')),
                ('nomina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otros_pagos', to='cfdi.nomina')),
                ('tipo_otro_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.tipootropago', verbose_name='Tipo de Otro Pago')),
            ],
            options={
                'verbose_name': 'Otro Pago',
                'verbose_name_plural': 'Otros Pagos',
            },
        ),
    ]
