# Generated by Django 5.1.4 on 2025-05-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0038_tipootropago_otropago'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcontratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfclaboral', models.CharField(max_length=13)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobanteNomina12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontrataciones', to='cfdi.comprobantenomina12')),
            ],
            options={
                'verbose_name': 'Subcontratación',
                'verbose_name_plural': 'Subcontrataciones',
            },
        ),
    ]
