# Generated by Django 5.1.4 on 2025-05-27 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0039_subcontratacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='entidad_presto_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfdi.estado', to_field='c_Estado', verbose_name='Entidad donde prestó el servicio'),
        ),
    ]
