# Generated by Django 5.1.4 on 2025-05-29 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0040_alter_nomina_entidad_presto_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deduccion',
            name='nomina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deducciones', to='cfdi.nomina'),
        ),
        migrations.AlterField(
            model_name='otropago',
            name='nomina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otros_pagos', to='cfdi.nomina'),
        ),
        migrations.AlterField(
            model_name='percepcion',
            name='nomina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='percepciones', to='cfdi.nomina'),
        ),
    ]
