# Generated by Django 5.1.4 on 2025-05-29 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0041_alter_deduccion_nomina_alter_otropago_nomina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otropago',
            name='nomina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otros_pagos', to='cfdi.nomina'),
        ),
    ]
