# Generated by Django 5.1 on 2025-05-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0042_alter_otropago_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='otropago',
            name='anio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otropago',
            name='remanente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otropago',
            name='saldoAfavor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otropago',
            name='subsidioCausado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
