# Generated by Django 5.1 on 2025-05-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0043_otropago_anio_otropago_remanente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoIncapacidad',
            fields=[
                ('c_TipoIncapacidad', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
        ),
    ]
