# Generated by Django 5.1 on 2025-05-30 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0044_tipoincapacidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='percepcion',
            name='dias_incapacidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias Incapacidad'),
        ),
        migrations.AddField(
            model_name='percepcion',
            name='importe_Monetario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Monetario'),
        ),
        migrations.AddField(
            model_name='percepcion',
            name='tipodeincapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.tipoincapacidad', verbose_name='Tipo de Incapacidad'),
        ),
    ]
