# Generated by Django 5.1 on 2025-05-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0045_percepcion_dias_incapacidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHoras',
            fields=[
                ('c_TipoHoras', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Clave')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
        ),
    ]
