# Generated by Django 5.1 on 2025-05-30 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0046_tipohoras'),
    ]

    operations = [
        migrations.AddField(
            model_name='percepcion',
            name='dias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dias Extra'),
        ),
        migrations.AddField(
            model_name='percepcion',
            name='horas_extra',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas Extra'),
        ),
        migrations.AddField(
            model_name='percepcion',
            name='importe_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Pagado'),
        ),
        migrations.AddField(
            model_name='percepcion',
            name='tipo_horas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.tipohoras', verbose_name='Horas Extra'),
        ),
    ]
