# Generated by Django 5.1.4 on 2025-06-02 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0047_percepcion_dias_percepcion_horas_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percepcion',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='percepcion',
            name='horas_extra',
        ),
        migrations.RemoveField(
            model_name='percepcion',
            name='importe_pagado',
        ),
        migrations.RemoveField(
            model_name='percepcion',
            name='tipo_horas',
        ),
        migrations.CreateModel(
            name='HorasExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_extra', models.IntegerField(blank=True, null=True, verbose_name='Horas Extra')),
                ('dias', models.IntegerField(blank=True, null=True, verbose_name='Dias Extra')),
                ('importe_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Pagado')),
                ('percepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horas_extra', to='cfdi.percepcion')),
                ('tipo_horas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.tipohoras', verbose_name='Horas Extra')),
            ],
            options={
                'verbose_name': 'Horas Extra',
                'verbose_name_plural': 'Horas Extras',
            },
        ),
    ]
