# Generated by Django 5.1.4 on 2025-06-02 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0048_remove_percepcion_dias_remove_percepcion_horas_extra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='percepcion',
            name='dias_incapacidad',
        ),
        migrations.RemoveField(
            model_name='percepcion',
            name='importe_Monetario',
        ),
        migrations.RemoveField(
            model_name='percepcion',
            name='tipodeincapacidad',
        ),
        migrations.CreateModel(
            name='Incapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_incapacidad', models.IntegerField(blank=True, null=True, verbose_name='Dias Incapacidad')),
                ('importe_Monetario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Importe Monetario')),
                ('percepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incapacidad', to='cfdi.percepcion')),
                ('tipo_incapacidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.tipoincapacidad', verbose_name='Tipo de Incapacidad')),
            ],
            options={
                'verbose_name': 'Incapacidad',
                'verbose_name_plural': 'Incapacidades',
            },
        ),
    ]
