# Generated by Django 5.1.4 on 2025-06-02 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0049_remove_percepcion_dias_incapacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incapacidad',
            name='Deduccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incapacidad', to='cfdi.deduccion'),
        ),
    ]
