# Generated by Django 5.1.4 on 2025-06-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0050_incapacidad_deduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incapacidad',
            name='Deduccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incapacidad_deduccion', to='cfdi.deduccion'),
        ),
        migrations.AlterField(
            model_name='subcontratacion',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Porcentaje'),
        ),
        migrations.AlterField(
            model_name='subcontratacion',
            name='rfclaboral',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC Laboral'),
        ),
    ]
