# Generated by Django 5.1.4 on 2025-06-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0051_alter_incapacidad_deduccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='monto_recurso_propio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto recurso propio'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='numero_dias_pagados',
            field=models.IntegerField(default=0, verbose_name='Número de días pagados'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salario base'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salario_diario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salario diario'),
        ),
    ]
