# Generated by Django 5.1.4 on 2025-06-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0052_alter_nomina_monto_recurso_propio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='monto_recurso_propio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto recurso propio'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='numero_dias_pagados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de días pagados'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Salario base'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='salario_diario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario diario'),
        ),
    ]
