# Generated by Django 5.1.4 on 2025-06-18 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0053_alter_nomina_monto_recurso_propio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autotransporte',
            options={'verbose_name': 'Autotransporte', 'verbose_name_plural': 'Autotransportes'},
        ),
        migrations.AlterModelOptions(
            name='cantidadtransportada',
            options={'verbose_name': 'Cantidad Transportada', 'verbose_name_plural': 'Cantidades Transportadas'},
        ),
        migrations.AlterModelOptions(
            name='detallemercanciamaritima',
            options={'verbose_name': 'Detalle de Mercancía (Marítimo)', 'verbose_name_plural': 'Detalles de Mercancía (Marítimo)'},
        ),
        migrations.AlterModelOptions(
            name='figuratransporte',
            options={'verbose_name': 'Figura de Transporte', 'verbose_name_plural': 'Figuras de Transporte'},
        ),
        migrations.AlterModelOptions(
            name='guiaidentificacion',
            options={'verbose_name': 'Guía de Identificación', 'verbose_name_plural': 'Guías de Identificación'},
        ),
        migrations.AlterModelOptions(
            name='mercancia',
            options={'verbose_name': 'Mercancia', 'verbose_name_plural': 'Mercancias'},
        ),
        migrations.AlterModelOptions(
            name='partetransporte',
            options={'verbose_name': 'Parte de Transporte', 'verbose_name_plural': 'Parte de Transporte'},
        ),
        migrations.AlterModelOptions(
            name='pedimento',
            options={'verbose_name': 'Pedimento', 'verbose_name_plural': 'Pedimentos'},
        ),
        migrations.AlterModelOptions(
            name='regimenaduaneroccptresuno',
            options={'verbose_name': 'Regimen Aduanero Ccp 31', 'verbose_name_plural': 'Regimen Aduanero Ccp 31'},
        ),
        migrations.AlterModelOptions(
            name='tipopercepcion',
            options={'verbose_name': 'Percepción', 'verbose_name_plural': 'Percepciones'},
        ),
        migrations.AlterModelOptions(
            name='transporteaereo',
            options={'verbose_name': 'Transporte Aéreo', 'verbose_name_plural': 'Transportes Aéreos'},
        ),
        migrations.AlterModelOptions(
            name='transporteferroviario',
            options={'verbose_name': 'Transporte Ferroviario', 'verbose_name_plural': 'Transportes Ferroviarios'},
        ),
        migrations.AlterModelOptions(
            name='transportemaritimo',
            options={'verbose_name': 'Transporte Marítimo', 'verbose_name_plural': 'Transportes Marítimos'},
        ),
        migrations.RemoveField(
            model_name='autotransporte',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='cantidadtransportada',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='detallemercanciamaritima',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='figuratransporte',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='guiaidentificacion',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='mercancia',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='partetransporte',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='pedimento',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='regimenaduaneroccptresuno',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='transporteaereo',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='transporteferroviario',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.RemoveField(
            model_name='transportemaritimo',
            name='FacturaCartaPorteTraslado',
        ),
        migrations.AddField(
            model_name='autotransporte',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autotransportes', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='cantidadtransportada',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantidades_transportadas', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='detallemercanciamaritima',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_mercancia_maritima', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='figuratransporte',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='figuras_transporte', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='guiaidentificacion',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guias_identificacion', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='mercancia',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mercancias', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='partetransporte',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partetransportes', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='pedimento',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='idUserCFDI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantillas', to='cfdi.userscfdi'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='imagen',
            field=models.ImageField(null=True, upload_to='plantillas/'),
        ),
        migrations.AddField(
            model_name='regimenaduaneroccptresuno',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regimenes_aduaneros', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='transporteaereo',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporteAereo', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='transporteferroviario',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transporteFerroviario', to='cfdi.comprobantecartaportetraslado'),
        ),
        migrations.AddField(
            model_name='transportemaritimo',
            name='comprobanteCartaPorteTraslado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transportes_maritimos', to='cfdi.comprobantecartaportetraslado'),
        ),
    ]
