# Generated by Django 5.1.4 on 2025-06-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0054_remove_plantilla_modelo_alter_autotransporte_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='tipo_comprobante',
            field=models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('N', 'Nómina'), ('P', 'Pago')], default='I', max_length=2),
        ),
    ]
