# Generated by Django 5.1.4 on 2025-06-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0055_plantilla_tipo_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='tipo_comprobante',
            field=models.CharField(choices=[('I', 'I'), ('E', 'E'), ('N', 'N'), ('P', 'P')], default='I', max_length=2),
        ),
    ]
