# Generated by Django 5.1.4 on 2025-06-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0056_alter_plantilla_tipo_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='tipo_comprobante',
            field=models.CharField(choices=[('I', 'Ingreso'), ('E', 'Egreso'), ('N', 'Nómina'), ('P', 'Pago')], default='I', max_length=2),
        ),
    ]
