# Generated by Django 5.1.4 on 2025-07-08 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0059_alter_plantilla_tipo_comprobante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptos',
            options={'ordering': ['id'], 'verbose_name': 'Concepto', 'verbose_name_plural': 'Conceptos'},
        ),
        migrations.AlterModelOptions(
            name='informacionaduanera',
            options={'ordering': ['fecha_fin_vigencia'], 'verbose_name': 'Información Aduanera', 'verbose_name_plural': 'Informaciones Aduaneras'},
        ),
        migrations.AddField(
            model_name='conceptos',
            name='complemento_tipo',
            field=models.CharField(blank=True, choices=[(None, 'Sin complemento'), ('cuenta_terceros', 'A Cuenta de Terceros'), ('cuenta_predial', 'Cuenta Predial'), ('informacion_aduanera', 'Información Aduanera'), ('parte', 'Parte')], max_length=30, null=True, verbose_name='Tipo de Complemento'),
        ),
        migrations.AlterField(
            model_name='informacionfiscal',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='estado de activación'),
        ),
        migrations.AlterField(
            model_name='informacionfiscal',
            name='idUserCFDI',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfdi.userscfdi'),
        ),
        migrations.CreateModel(
            name='PedimentoCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.PositiveIntegerField()),
                ('numero', models.CharField(blank=True, max_length=21, null=True)),
                ('aduana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cfdi.aduana')),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='cfdi.conceptos')),
                ('patente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cfdi.patenteaduanal')),
            ],
            options={
                'db_table': 'cfdi_pedimentocfdi',
                'unique_together': {('concepto', 'aduana', 'patente', 'ejercicio')},
            },
        ),
    ]
