# Generated by Django 5.1.4 on 2025-07-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0060_alter_conceptos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionfiscal',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
