# Generated by Django 5.1.4 on 2025-07-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0061_alter_informacionfiscal_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='fechaPago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
