# Generated by Django 5.1.4 on 2025-07-15 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0062_alter_comprobante_fechapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparacionIndemnizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Pagado')),
                ('num_anos_servicio', models.IntegerField(blank=True, null=True, verbose_name='Número de Años de Servicio')),
                ('ultimo_sueldo_mens_ord', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Último Sueldo Mensual Ordinario')),
                ('ingreso_acumulable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingreso Acumulable')),
                ('ingreso_no_acumulable', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingreso No Acumulable')),
                ('percepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='separacion_indemnizacion', to='cfdi.percepcion')),
            ],
            options={
                'verbose_name': 'Separación Indemnización',
                'verbose_name_plural': 'Separaciones Indemnización',
            },
        ),
    ]
