# Generated by Django 5.1.4 on 2025-07-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0063_separacionindemnizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='impuestos',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
