# Generated by Django 5.1.4 on 2025-07-16 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0064_impuestos_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='c_Moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfdi.moneda'),
        ),
    ]
