# Generated by Django 5.1.4 on 2025-07-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0065_alter_comprobante_c_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptos',
            name='descuento_incluido',
            field=models.BooleanField(default=False, verbose_name='Descuento incluido'),
        ),
        migrations.AddField(
            model_name='conceptos',
            name='descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
