# Generated by Django 5.1.4 on 2025-07-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0066_conceptos_descuento_incluido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptos',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
