# Generated by Django 5.1.4 on 2025-07-24 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0067_alter_conceptos_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteEgreso',
            fields=[
            ],
            options={
                'verbose_name': 'Comprobante de Egreso',
                'verbose_name_plural': 'Comprobantes de Egreso',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cfdi.comprobante',),
        ),
        migrations.CreateModel(
            name='ComprobanteTraslado',
            fields=[
            ],
            options={
                'verbose_name': 'Comprobante de Traslado',
                'verbose_name_plural': 'Comprobantes de Traslado',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cfdi.comprobante',),
        ),
    ]
