# Generated by Django 5.1.4 on 2025-07-28 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0068_comprobanteegreso_comprobantetraslado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='c_CodigoPostal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cfdi.codigopostal'),
        ),
    ]
