# Generated by Django 5.1.4 on 2025-07-30 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0069_alter_nomina_c_codigopostal'),
    ]

    operations = [
        migrations.CreateModel(
            name='JubilacionPensionRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_una_exhibicion', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Una Exhibicion')),
                ('ingreso_acumulable', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Ingreso Acumulable')),
                ('ingreso_no_acumulable', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Ingreso No Acumulable')),
                ('percepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jubilacion_pension_retiro', to='cfdi.percepcion')),
            ],
            options={
                'verbose_name': 'Jubilación Pensión Retiro',
                'verbose_name_plural': 'Jubilaciones Pensiones Retiro',
            },
        ),
    ]
