# Generated by Django 5.1.4 on 2025-07-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0070_jubilacionpensionretiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='jubilacionpensionretiro',
            name='total_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Pagado'),
        ),
    ]
