# Generated by Django 5.1.4 on 2025-07-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0071_jubilacionpensionretiro_total_pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jubilacionpensionretiro',
            name='total_pagado',
        ),
        migrations.AlterField(
            model_name='jubilacionpensionretiro',
            name='ingreso_no_acumulable',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingreso No Acumulable'),
        ),
    ]
