# Generated by Django 5.1.4 on 2025-08-02 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0072_remove_jubilacionpensionretiro_total_pagado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteemitido',
            name='cancelado',
            field=models.BooleanField(default=False, help_text='Indica si el comprobante ha sido cancelado', verbose_name='Comprobante Cancelado'),
        ),
        migrations.CreateModel(
            name='CancelacionCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_original', models.CharField(max_length=36)),
                ('motivo', models.CharField(choices=[('01', 'Comprobante emitido con errores con relación'), ('02', 'Comprobante emitido con errores sin relación'), ('03', 'No se llevó a cabo la operación'), ('04', 'Operación nominativa relacionada en una factura global')], max_length=2)),
                ('uuid_sustitucion', models.CharField(blank=True, max_length=36, null=True)),
                ('fecha_inicio_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('estado_cancelacion', models.CharField(blank=True, max_length=100, null=True)),
                ('respuesta_sat', models.TextField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=False)),
                ('cancelado', models.BooleanField(default=False)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelaciones', to='cfdi.comprobanteemitido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfdi.userscfdi')),
            ],
            options={
                'verbose_name': 'Cancelación de CFDI',
                'verbose_name_plural': 'Cancelaciones de CFDI',
                'ordering': ['-fecha_inicio_cancelacion'],
            },
        ),
    ]
