# Generated by Django 5.1.4 on 2025-08-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0073_comprobanteemitido_cancelado_cancelacioncfdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteemitido',
            name='detallesError',
            field=models.TextField(blank=True, help_text='Detalles del error si el comprobante no se pudo emitir correctamente', null=True, verbose_name='Detalles del Error'),
        ),
        migrations.AlterField(
            model_name='comprobanteemitido',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='comprobanteemitido',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='comprobanteemitido',
            name='uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='UUID'),
        ),
    ]
