# Generated by Django 5.1.4 on 2025-08-20 20:13

import cfdi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cfdi', '0075_groupmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruposCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'gruposCFDI',
                'verbose_name_plural': 'gruposCFDI',
            },
            managers=[
                ('objects', cfdi.models.GroupManager()),
            ],
        ),
    ]
