# Generated by Django 5.1.4 on 2025-08-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0076_gruposcfdi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruposcfdi',
            options={'verbose_name': 'grupoCFDI', 'verbose_name_plural': 'gruposCFDI'},
        ),
    ]
