# Generated by Django 5.1.4 on 2025-08-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0077_alter_gruposcfdi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruposcfdi',
            options={'verbose_name': 'grupoCFDI', 'verbose_name_plural': 'grupos CFDI'},
        ),
    ]
