# Generated by Django 5.1.4 on 2025-08-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0078_alter_gruposcfdi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmeta',
            options={'verbose_name': 'Grupo', 'verbose_name_plural': 'Detalle grupos'},
        ),
    ]
