# Generated by Django 5.1.4 on 2025-08-22 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0079_alter_groupmeta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscfdi',
            name='negocio_activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_cfdi_que_usan_este_negocio', to='cfdi.informacionfiscal'),
        ),
    ]
