# Generated by Django 5.1.4 on 2025-08-25 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0080_userscfdi_negocio_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraCFDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_creacion', models.GenericIPAddressField(blank=True, null=True)),
                ('ubicacion_creacion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_edicion', models.DateTimeField(blank=True, null=True)),
                ('ip_edicion', models.GenericIPAddressField(blank=True, null=True)),
                ('ubicacion_edicion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_timbrado', models.DateTimeField(blank=True, null=True)),
                ('ip_timbrado', models.GenericIPAddressField(blank=True, null=True)),
                ('ubicacion_timbrado', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('ip_cancelacion', models.GenericIPAddressField(blank=True, null=True)),
                ('ubicacion_cancelacion', models.CharField(blank=True, max_length=100, null=True)),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdi_cancelados', to=settings.AUTH_USER_MODEL)),
                ('comprobante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='cfdi.comprobante')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdi_creados', to=settings.AUTH_USER_MODEL)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdi_editados', to=settings.AUTH_USER_MODEL)),
                ('timbrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfdi_timbrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
