# Generated by Django 5.1.4 on 2025-09-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0081_bitacoracfdi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacoracfdi',
            options={'verbose_name': 'Bitacora CFDI', 'verbose_name_plural': 'Bitacoras CFDI'},
        ),
    ]
