# Generated by Django 5.1.4 on 2025-11-10 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0082_alter_bitacoracfdi_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comprobante",
            options={
                "verbose_name": "Comprobante",
                "verbose_name_plural": "Comprobantes",
            },
        ),
        migrations.CreateModel(
            name="UserTimbreCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                ("contador_actual", models.PositiveIntegerField(default=0)),
                ("limite_timbres", models.PositiveIntegerField()),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_suspension", models.DateField(blank=True, null=True)),
                ("razon_suspension", models.TextField(blank=True)),
                (
                    "user_cfdi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timbres",
                        to="cfdi.userscfdi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteo de Timbres",
                "verbose_name_plural": "Conteos de Timbres",
                "ordering": ["-periodo_inicio"],
                "unique_together": {("user_cfdi", "periodo_inicio", "periodo_fin")},
            },
        ),
    ]
