# Generated by Django 5.1.4 on 2025-11-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0083_remove_plantilla_modelo_alter_comprobante_options_and_more"),
        ("console", "0024_alter_service_enviar_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertimbrecount",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="console.plan",
            ),
        ),
    ]
