# Generated by Django 5.1.4 on 2025-11-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0084_usertimbrecount_plan"),
        ("console", "0024_alter_service_enviar_pdf"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usertimbrecount",
            unique_together={("user_cfdi", "periodo_inicio", "periodo_fin", "plan")},
        ),
    ]
