# Generated by Django 5.1 on 2025-11-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfdi', '0085_alter_usertimbrecount_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacionfiscal',
            name='manifiesto_contrato_pdf',
            field=models.TextField(blank=True, null=True, verbose_name='Contrato de manifiesto (PDF)'),
        ),
        migrations.AddField(
            model_name='informacionfiscal',
            name='manifiesto_contrato_xml',
            field=models.TextField(blank=True, null=True, verbose_name='Contrato de manifiesto (XML)'),
        ),
        migrations.AddField(
            model_name='informacionfiscal',
            name='manifiesto_firmado',
            field=models.BooleanField(default=False, verbose_name='¿Manifiesto firmado?'),
        ),
        migrations.AddField(
            model_name='userscfdi',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
