# Generated by Django 5.1.4 on 2025-12-03 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0086_informacionfiscal_manifiesto_contrato_pdf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informacionfiscal",
            name="calle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="informacionfiscal",
            name="ciudad",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="informacionfiscal",
            name="colonia",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="informacionfiscal",
            name="correo_electronico",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo electrónico"
            ),
        ),
        migrations.AlterField(
            model_name="informacionfiscal",
            name="estado",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="informacionfiscal",
            name="municipio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="informacionfiscal",
            name="numero_exterior",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="No. Ext."
            ),
        ),
        migrations.AlterField(
            model_name="informacionfiscal",
            name="telefono",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
