# Generated by Django 5.1.4 on 2026-01-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cfdi", "0088_pdfpersonalizado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informacionglobal",
            name="Anio",
            field=models.CharField(default="2026", max_length=4),
        ),
    ]
