# Generated by Django 5.0.3 on 2024-12-03 02:20

import django.db.models.deletion
import invoice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('console', '0022_user_service_aceptarterminos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellidoP', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido Paterno')),
                ('apellidoM', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=150, verbose_name='Correo Electronico')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefono')),
                ('tipoCliente', models.CharField(blank=True, choices=[('O', 'OnDemant'), ('P', 'Prepago')], default='P', max_length=20)),
                ('Cer', models.FileField(blank=True, null=True, upload_to='cers/')),
                ('Key', models.FileField(blank=True, null=True, upload_to='keys/')),
                ('passphrase', models.CharField(blank=True, max_length=150, verbose_name='Passphrase')),
                ('calle', models.CharField(blank=True, max_length=150, verbose_name='Calle')),
                ('numeroExterior', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero Exterior')),
                ('numeroInterior', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero Interior')),
                ('colonia', models.CharField(blank=True, max_length=150, verbose_name='Colonia')),
                ('localidad', models.CharField(blank=True, max_length=150, verbose_name='Localidad')),
                ('municipio', models.CharField(blank=True, max_length=150, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=150, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, max_length=150, null=True, verbose_name='pais')),
                ('codigoPostal', models.CharField(blank=True, max_length=150, verbose_name='Codigo Postal')),
                ('tipoReceptor', models.CharField(blank=True, default='moral', max_length=15)),
                ('cer_base64', models.TextField(blank=True, null=True, verbose_name='Certificado Base64')),
                ('key_base64', models.TextField(blank=True, null=True, verbose_name='Clave Privada Base64')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoicePermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_my_soap_application_cancel', 'Can view SOAP application cancellation'), ('view_my_soap_application_stamp', 'Can view SOAP application stamp')),
            },
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('estado_firma', models.CharField(choices=[('true', 'FIRMADO'), ('false', 'SIN_FIRMAR')], default='false', max_length=10)),
                ('contratoXML', models.TextField(blank=True, null=True)),
                ('contratoPDF', models.TextField(blank=True, null=True)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrato_cliente', to='invoice.cliente')),
            ],
            options={
                'verbose_name': 'Gestion_firma',
                'verbose_name_plural': 'Gestion_firmas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LogStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(blank=True, max_length=255, null=True)),
                ('Fecha', models.CharField(blank=True, max_length=255, null=True)),
                ('Emisor', models.CharField(blank=True, max_length=13, null=True)),
                ('CodEstatus', models.CharField(blank=True, max_length=255, null=True)),
                ('SatSeal', models.TextField(blank=True, null=True)),
                ('NoCertificadoSAT', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('firmada', 'Firmada'), ('timbrada', 'Timbrada'), ('firmada_timbrada', 'Firmada y Timbrada'), ('sin_timbrar', 'Sin Timbrar')], max_length=20)),
                ('typeOperation', models.CharField(choices=[('stamp', 'Stamp'), ('cancel', 'Cancel'), ('sign_stamp', 'Sign and Stamp')], max_length=20)),
                ('fechaLog', models.DateTimeField(auto_now_add=True, verbose_name='FechaRegistro')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idUser_ServicePlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.service_plan')),
            ],
            options={
                'verbose_name': 'LogStamp',
                'verbose_name_plural': 'LogStamps',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilFiscalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('apellidoP', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido Paterno')),
                ('apellidoM', models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=150, verbose_name='Correo Electronico')),
                ('rfc', models.CharField(blank=True, max_length=13, unique=True, verbose_name='RFC')),
                ('curp', models.CharField(blank=True, max_length=18, verbose_name='CURP')),
                ('telefono', models.PositiveIntegerField(blank=True, null=True, verbose_name='Telefono')),
                ('tipoCliente', models.CharField(blank=True, choices=[('O', 'OnDemant'), ('P', 'Prepago')], default='P', max_length=20)),
                ('Cer', models.FileField(blank=True, null=True, upload_to='cers/')),
                ('Key', models.FileField(blank=True, null=True, upload_to='keys/')),
                ('passphrase', models.CharField(blank=True, max_length=150, verbose_name='Passphrase')),
                ('calle', models.CharField(blank=True, max_length=150, verbose_name='Calle')),
                ('numeroExterior', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero Exterior')),
                ('numeroInterior', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero Interior')),
                ('colonia', models.CharField(blank=True, max_length=150, verbose_name='Colonia')),
                ('localidad', models.CharField(blank=True, max_length=150, verbose_name='Localidad')),
                ('municipio', models.CharField(blank=True, max_length=150, verbose_name='Municipio')),
                ('estado', models.CharField(blank=True, max_length=150, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, max_length=150, null=True, verbose_name='pais')),
                ('codigoPostal', models.CharField(blank=True, max_length=150, verbose_name='Codigo Postal')),
                ('tipoReceptor', models.CharField(blank=True, default='moral', max_length=15)),
                ('localizado', models.BooleanField(default=False, verbose_name='Localizado en una zona fronteriza')),
                ('compartir_datos', models.BooleanField(default=False, verbose_name='Compartir datos fiscales (live connect)')),
                ('mostrar_razon_social', models.BooleanField(default=False, verbose_name='Mostrar nombre o razón social en CFDI')),
                ('mostrar_domicilio', models.BooleanField(default=False, verbose_name='Mostrar en domicilio fiscal CFDI')),
                ('mostrar_direccion_expedicion', models.BooleanField(default=False, verbose_name='Mostrar dirección de expedición en CFDI')),
                ('mostrar_nombre_cliente', models.BooleanField(default=False, verbose_name='Mostrar nombre o razón social de cliente en CFDI')),
                ('mostrar_direccion_cliente', models.BooleanField(default=False, verbose_name='Mostrar dirección del cliente en CFDI')),
                ('regimen_Fiscal', models.CharField(blank=True, choices=[('601', 'General de Ley Personas Morales'), ('603', 'Personas Morales con Fines no Lucrativos'), ('605', 'Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', 'Arrendamiento'), ('607', 'Régimen de Enajenación o Adquisición de Bienes'), ('608', 'Demás ingresos'), ('609', 'Consolidación'), ('610', 'Residentes en el Extranjero sin Establecimiento Permanente en Máxico'), ('611', 'Ingresos por Dividendos (socios y accionistas)'), ('612', 'Personas Físicas con Actividades Empresariales y Profesionales'), ('614', 'Ingresos por intereses'), ('615', 'Régimen de los ingresos por obtención de premios'), ('616', 'Sin obligaciones fiscales'), ('620', 'Sociedades Cooperativas de Producción que optan por diferir sus ingresos'), ('621', 'Incorporación Fiscal'), ('622', 'Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras'), ('623', 'Opcional para Grupos de Sociedades'), ('624', 'Coordinados'), ('625', 'Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas'), ('626', 'Régimen Simplificado de Confianza'), ('628', 'Hidrocarburos'), ('629', 'De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales'), ('630', 'Enajenación de acciones en bolsa de valores')], default='601', max_length=20)),
                ('cer_base64', models.TextField(blank=True, null=True, verbose_name='Certificado Base64')),
                ('key_base64', models.TextField(blank=True, null=True, verbose_name='Clave Privada Base64')),
                ('fecha', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Firma')),
                ('estado_firma', models.CharField(choices=[('true', 'FIRMADO'), ('false', 'SIN_FIRMAR')], default='false', max_length=10)),
                ('contratoXML', models.TextField(blank=True, null=True)),
                ('contratoPDF', models.TextField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('estatus', models.CharField(choices=[('A', 'Activar'), ('S', 'Suspender')], default='S', max_length=20)),
                ('validado', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TimbreUserPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('A', 'Activado'), ('S', 'Suspendido')], default='A', max_length=20)),
                ('isOnDemmand', models.BooleanField(default=False)),
                ('stamp', models.IntegerField(default=0)),
                ('cont_stamped_user', models.IntegerField(default=0)),
                ('cont_stamped_day', models.IntegerField(default=0)),
                ('idUser_ServicePlan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='console.user_service')),
                ('userInvoice', models.ForeignKey(default=invoice.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timbre User Perfil',
                'verbose_name_plural': 'Timbres User Perfil',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxpayer_id', models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('userName', models.CharField(max_length=150, verbose_name='Nombre de Usuario')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('estatus', models.CharField(blank=True, choices=[('true', 'Activo'), ('false', 'Suspendido')], default='true', max_length=20)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('idUserParent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_tokens', to=settings.AUTH_USER_MODEL)),
                ('idUserToken', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gestion_token',
                'verbose_name_plural': 'Gestion_tokens',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('A', 'Activar'), ('S', 'Suspender')], default='A', max_length=20)),
                ('countStamp', models.IntegerField(default=0, verbose_name='Contador de timbres')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.cliente')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_Cliente',
                'verbose_name_plural': 'User_Clientes',
                'ordering': ['id'],
                'unique_together': {('idCliente', 'idUser')},
            },
        ),
        migrations.CreateModel(
            name='Timbre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('estatus', models.CharField(choices=[('A', 'Activado'), ('S', 'Suspendido')], default='A', max_length=20)),
                ('isOnDemmand', models.BooleanField(default=False)),
                ('stamp', models.IntegerField(default=0)),
                ('cont_stamped_cliente', models.IntegerField(default=0)),
                ('cont_stamped_day', models.IntegerField(default=0)),
                ('user_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timbres_de_cliente', to='invoice.user_cliente')),
            ],
        ),
    ]
