# Generated by Django 5.1.4 on 2025-11-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfilfiscaluser",
            name="rfc",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="RFC"
            ),
        ),
        migrations.AlterField(
            model_name="perfilfiscaluser",
            name="telefono",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telefono"
            ),
        ),
    ]
