"""add event_type to webhook notification queue

Revision ID: 04dddc140b18
Revises: 3df6cb7be27d
Create Date: 2026-07-20 12:35:29.935916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '04dddc140b18'
down_revision: Union[str, Sequence[str], None] = '3df6cb7be27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'webhooknotificationqueue',
        sa.Column(
            'event_type',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default='checkout_completed',
        ),
    )
    op.create_index(op.f('ix_webhooknotificationqueue_event_type'), 'webhooknotificationqueue', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooknotificationqueue_event_type'), table_name='webhooknotificationqueue')
    op.drop_column('webhooknotificationqueue', 'event_type')
    # ### end Alembic commands ###
