"""add stripe_customer_id to subscription

Revision ID: 2db8b3141d33
Revises: 04dddc140b18
Create Date: 2026-08-10 17:00:19.671737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2db8b3141d33'
down_revision: Union[str, Sequence[str], None] = '04dddc140b18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_subscription_stripe_customer_id'), 'subscription', ['stripe_customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_stripe_customer_id'), table_name='subscription')
    op.drop_column('subscription', 'stripe_customer_id')
    # ### end Alembic commands ###
