"""add webhook notification queue

Revision ID: 3df6cb7be27d
Revises: 26e708a3d694
Create Date: 2026-06-19 15:13:43.679919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3df6cb7be27d'
down_revision: Union[str, Sequence[str], None] = '26e708a3d694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooknotificationqueue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('billing_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('date_cutoff', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhooknotificationqueue_next_retry_at'), 'webhooknotificationqueue', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_webhooknotificationqueue_subscription_id'), 'webhooknotificationqueue', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooknotificationqueue_subscription_id'), table_name='webhooknotificationqueue')
    op.drop_index(op.f('ix_webhooknotificationqueue_next_retry_at'), table_name='webhooknotificationqueue')
    op.drop_table('webhooknotificationqueue')
    # ### end Alembic commands ###
