version: "3.9"

services:

  # ============================================
  # POSTGRES (API Files)
  # ============================================
  api_files_postgres:
    image: postgres:17
    container_name: api_files_postgres
    restart: always
    environment:
      POSTGRES_USER: api_files_user
      POSTGRES_PASSWORD: api_files_user_pa$$word
      POSTGRES_DB: api_files_db
      TZ: America/Mexico_City
      PGTZ: America/Mexico_City
    command: ["-c", "max_connections=300"]
    ports:
      - "5433:5432"
    volumes:
      - pgdata_api:/var/lib/postgresql/data
    networks:
      - apis_net
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 12G
        reservations:
          cpus: "0.1"
          memory: 1024M
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"

  # ============================================
  # API Files
  # ============================================
  api_support:
    build: ./services/api_files
    container_name: api_files
    env_file: .env
    depends_on:
      - api_files_postgres
    networks:
      - apis_net

  # ============================================
  # POSTGRES (Storage)
  # ============================================
  storage_postgres:
    image: postgres:16
    container_name: files_postgres
    environment:
      POSTGRES_USER: files_postgres_storage
      POSTGRES_PASSWORD: files_postgres_storage_pa$$word
      POSTGRES_DB: files_postgres_storage_db
    volumes:
      - pgdata_storage:/var/lib/postgresql/data
    networks:
      - apis_net

  # ============================================
  # MONGO DB (Storage)
  # ============================================
  mongo:
    image: mongo:7
    container_name: files_mongo
    volumes:
      - mongodata:/data/db
    networks:
      - apis_net

  # ============================================
  # MINIO (Archivos)
  # ============================================
  minio:
    image: quay.io/minio/minio
    container_name: files_minio
    command: server /data --console-address ":9001"
    env_file: .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - apis_net

# ============================================
# Redes
# ============================================
networks:
  apis_net:
    driver: bridge

# ============================================
# Volúmenes
# ============================================
volumes:
  pgdata_api:
  pgdata_storage:
  mongodata:
  minio_data:
